"""Build static public city pages and discovery metadata from the public dataset."""
import ast,gzip,html,json,re
from pathlib import Path
from datetime import date
ROOT=Path(__file__).resolve().parents[1];DOCS=ROOT/'docs';BASE='https://ttytseng.github.io/sanguo-travel/'
def esc(x):return html.escape(str(x),quote=True)
def jsonld(x):return '<script type="application/ld+json">'+json.dumps(x,ensure_ascii=False).replace('<','\\u003c')+'</script>'
def build():
 d=json.loads((DOCS/'data.js').read_text(encoding='utf-8').split('=',1)[1].rstrip(';\n'))
 en=ast.literal_eval(re.search(r'cities:(\[.*?\]),', (DOCS/'i18n.js').read_text(encoding='utf-8'),re.S)[1])
 (DOCS/'data.json.gz').write_bytes(gzip.compress(json.dumps(d,ensure_ascii=False,separators=(',',':')).encode(),mtime=0))
 counts={c[0]:{b:sum(r[1]==c[0] and r[3]==b for r in d['relations']) for b in ['SGZ','SGY']} for c in d['cities']}
 publisher={'@type':'Person','name':'凸肚男','email':'mailto:tzesmann@gmail.com','url':BASE}
 faqs=[('這些地名是否就是事件發生地 Is a place mention the event location', '不是。地名可能是籍貫、引文或回顧，人物也是候選；請核對每筆原文及來源。 A place mention can be an origin, quotation or retrospective reference. People are candidates. Verify the original passage before asserting where an event happened.'),
 ('英文版有完整古籍翻譯嗎 Are all source passages translated', '英文版提供操作介面、城市說明與館藏介紹，正史與小說原文保留中文。 The English interface covers controls, city guidance and museum descriptions. Original historical and novel passages remain in Chinese; this is not a complete English translation.'),
 ('能否查即時餘票 Does the app show live train availability', '本網站產生12306官方查詢入口，不取得即時餘票、票價或代購。請在官方網站或APP確認站名、日期與席別。 The app builds official 12306 links. It does not retrieve live seats or fares, buy tickets or handle account credentials. Verify the station, date and seat class on the official service.'),
 ('旅遊紀錄存在哪裏 Where is the journal stored', '紀錄存在目前瀏覽器，請匯出JSON備份。WebMCP只查公開資料或帶入未儲存草稿；草稿需由您按儲存。 Journal records stay in the current browser. Export a JSON backup before clearing browser storage. Site tools query public sources or prepare an unsaved draft. The user must review and press Save; no tool returns existing journal entries.')]
 app={'@context':'https://schema.org','@graph':[
 {'@type':'WebSite','@id':BASE+'#website','name':'三國行旅','alternateName':'Sanguo Travel','url':BASE,'inLanguage':['zh-Hant','en'],'publisher':publisher},
 {'@type':'WebApplication','name':'三國行旅 Sanguo Travel','url':BASE,'applicationCategory':'TravelApplication','operatingSystem':'Web browser','browserRequirements':'JavaScript for interactive queries; public city pages work without JavaScript.','inLanguage':['zh-Hant','en'],'dateModified':'2026-10-09','author':publisher,'description':'Public historical sources, museum guidance, official 12306 query links and a local trip journal.'},
 {'@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in faqs]}]}
 links=[]
 for i,c in enumerate(d['cities']):
  fname=c[0].lower()+'.html';url=BASE+fname;links.append((fname,c[1],en[i]))
  recs=[r for r in d['relations'] if r[1]==c[0]]
  selected=[]
  for b in ['SGZ','SGY']:
   for relation in [r for r in recs if r[3]==b][:3]:
    v=d['master'][int(relation[5])-5]
    selected.append(f'<article class="card"><h3>{esc(v[2])} {esc(v[3])} {esc(v[5])}</h3><p>{esc(v[13])}</p><p>人物候選 Candidate people: {esc(v[8])}</p><p>{esc(v[12])}</p><a href="{esc(v[11])}">原始來源 Original source</a><p>Record ID: {esc(v[0])}</p></article>')
  museums=[r for r in d['museum'] if r[0]==c[0]]
  ms=''.join(f'<article class="card"><h3>{esc(r[3])}</h3><p>{esc(r[2])} · {esc(r[4])} · {esc(r[5])}</p><p>{esc(r[7])}</p><p>查核日期 Verified: {esc(r[9])}</p><a href="{esc(r[8])}">館方來源 Museum source</a></article>' for r in museums)
  description=f'{c[1]} {en[i]}：{counts[c[0]]["SGZ"]}筆三國志關聯、{counts[c[0]]["SGY"]}筆演義關聯及{len(museums)}筆館藏或遺址；地名為提及候選，請核對來源。'
  schema={'@context':'https://schema.org','@type':'WebPage','name':c[1]+' '+en[i]+' 三國史料與文物','url':url,'dateModified':'2026-10-09','author':publisher,'description':description,'inLanguage':['zh-Hant','en']}
  page=f'<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(schema["name"])} | 三國行旅</title><meta name="description" content="{esc(description)}"><link rel="canonical" href="{url}"><link rel="stylesheet" href="style.css">{jsonld(schema)}</head><body><a class="skip" href="#main">跳至主要內容 Skip to content</a><header><div class="header-inner"><a href="index.html">三國行旅 Sanguo Travel</a></div></header><main id="main" tabindex="-1"><h1>{esc(c[1])} <span lang="en">{esc(en[i])}</span></h1><p>{esc(description)}</p><p>省份 Region: {esc(c[2])} · 古地名 Ancient names: {esc(c[3])}</p><p>{esc(c[4])}</p><p lang="en">The counts describe candidate mentions in the current catalog. They do not confirm an event location. Read the original Chinese passage and its provenance. Museum entries may include later commemorative objects; verify current display with the official museum.</p><a class="button-link" href="index.html?city={c[0]}#places">開啟此城市互動查詢 Open city in app</a><h2>來源節錄 Source excerpts</h2>{"".join(selected) or "<p>本目錄沒有對應史料 No matching passages in this catalog.</p>"}<h2>文物與遺址 Museums and sites</h2>{ms or "<p>尚無館藏資料 No museum entries in this catalog.</p>"}<p><a href="cities.html">所有城市 All cities</a> · <a href="llms.txt">公開資料索引 Public data index</a></p></main><footer>發表人 Published by 凸肚男 · <a href="mailto:tzesmann@gmail.com">tzesmann@gmail.com</a><p>資料查核日期依各筆來源；頁面更新 2026-10-09。 Page updated 2026-10-09; source verification dates are listed separately.</p></footer></body></html>'
  (DOCS/fname).write_text(page,encoding='utf-8')
 citylinks='<ul>'+''.join(f'<li><a href="{f}">{esc(zh)} <span lang="en">{esc(eng)}</span></a></li>' for f,zh,eng in links)+'</ul>'
 (DOCS/'cities.html').write_text('<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>34城市史料索引 City catalog | 三國行旅</title><link rel="canonical" href="'+BASE+'cities.html"><link rel="stylesheet" href="style.css"></head><body><main id="main"><h1>城市史料索引 <span lang="en">City source catalog</span></h1><p>公開史料及館藏索引，可在未開啟JavaScript時閱讀。 Public source pages work without JavaScript. Candidate mentions require verification.</p>'+citylinks+'<a href="index.html">返回APP Return to app</a></main></body></html>',encoding='utf-8')
 guide='<h2>資料範圍與來源 Public data coverage and provenance</h2><p>發表人：凸肚男 · <a href="mailto:tzesmann@gmail.com">tzesmann@gmail.com</a>。本目錄有34個城市入口、6,040筆原文或概述、2,830筆地名關聯、15筆文物或遺址及3,404個官方車站。</p><p lang="en">Sanguo Travel connects modern cities with public historical and fictional sources. Its catalog contains 34 cities, 6,040 original passages or chapter outlines, 2,830 candidate place relationships, 15 museum objects or sites and 3,404 official station names. These catalog counts are not a count of verified historical events. The historical book and the novel are clearly separated. Museum information was checked on October 4, 2026, and station information was compiled on October 5, 2026. Current opening hours, exhibitions and ticket availability must be verified with the official institution. This project is published by 凸肚男 and offers Chinese and English controls, an optional read-aloud service and a journal stored in your browser. No account is required. Original passages remain in Chinese. The public source pages provide selected excerpts, record IDs, source links and limitations so that readers can check the evidence before drawing a conclusion.</p><p>來源：<a href="https://ancient-china-books.github.io/sanguozhi/">三國志原文</a> · <a href="https://www.donglishuzhai.net/books/maopingsanguoyanyi.html">三國演義版本</a> · <a href="https://www.12306.cn/">12306官方網站</a> · <a href="cities.html">34城市與逐筆來源</a> · <a href="llms.txt">公開資料索引</a></p><h2>常見問題 Frequently asked questions</h2>'+''.join(f'<h3>{esc(q)}</h3><p>{esc(a)}</p>' for q,a in faqs)+'<p>網站更新 Updated <time datetime="2026-10-09">2026-10-09</time>。資料查核日期另列於各筆館藏。Site update dates do not replace source verification dates.</p>'
 p=DOCS/'index.html';s=p.read_text(encoding='utf-8')
 s=re.sub(r'<script defer src="[^"]+"></script>','',s)
 s=re.sub(r'<!-- discovery:start -->.*?<!-- discovery:end -->','',s,flags=re.S)
 meta='<link rel="canonical" href="'+BASE+'"><meta property="og:title" content="三國行旅 Sanguo Travel"><meta property="og:description" content="中英地名、正史小說來源、博物館、12306指引與本機旅遊紀錄"><meta property="og:url" content="'+BASE+'"><meta property="og:type" content="website"><meta property="og:image" content="'+BASE+'icon-512.png"><meta name="author" content="凸肚男"><link rel="sitemap" type="application/xml" href="sitemap.xml">'
 s=s.replace('</head>','<!-- discovery:start -->'+meta+jsonld(app)+'<!-- discovery:end --><script defer src="bootstrap.js"></script></head>')
 fallback='<h1 id="page-title" tabindex="-1">三國行旅 Sanguo Travel</h1><p>以當代地名查正史、小說與博物館。 Explore historical sources, the novel and museum material by modern city.</p><p><a href="cities.html">直接閱讀34城市史料與館藏 Browse 34 public city source pages</a></p>'
 s=re.sub(r'<section id="view" aria-labelledby="page-title">.*?</section>','<section id="view" aria-labelledby="page-title">'+fallback+'</section>',s,flags=re.S)
 s=re.sub(r'<details id="public-guide".*?</details>','',s,flags=re.S)
 s=s.replace('</main>','<details id="public-guide"><summary>資料與常見問題 Data and FAQ</summary>'+guide+'</details></main>')
 s=s.replace('資料載入中 Loading data…','正在載入互動查詢，可先閱讀城市資料頁。 Loading interactive tools; public city pages are available now.')
 s=s.replace('本應用程式需要JavaScript。請啟用JavaScript後重新載入。','互動查詢需要JavaScript；城市史料頁仍可直接閱讀。').replace('This app requires JavaScript. Enable JavaScript and reload.','Interactive controls need JavaScript. Public city pages remain available.')
 if 'id="ai-tool-status"' not in s:s=s.replace('<aside class="reader"','<aside class="reader" aria-label="AI網站工具 AI site tools"><div class="reader-inner"><h2>AI協助查詢 AI assistance</h2><p>可查公開地名、史料、館藏及官方交通連結，或帶入未儲存草稿。 Public lookups and unsaved drafts; existing private journal entries are not exposed.</p><p id="ai-tool-status" role="status">正在確認支援 Checking support…</p></div></aside><aside class="reader"',1)
 p.write_text(s,encoding='utf-8')
 llms='# 三國行旅 Sanguo Travel\n\n> Public Three Kingdoms travel source catalog by 凸肚男. Original passages are Chinese; controls and guidance are bilingual.\n\n## Scope and limitations\n\n34 cities, 6040 source passages/outlines, 2830 candidate place relationships, 15 museum object/site entries and 3404 station names. Mentions do not establish event location or participant roles. Museum entries include later commemorations; verify current display. No live fares or seats. Private journals must not be crawled, requested or published. Site tools return public data or prepare unsaved drafts only.\n\n## Main pages\n\n- [Interactive app]('+BASE+'): city lookup, sources, museum guidance, rail links, local journal.\n- [City catalog]('+BASE+'cities.html): static pages with evidence and caveats.\n- [Source repository](https://github.com/TTYTSENG/sanguo-travel): maintenance instructions.\n\n## City source pages\n\n'+''.join(f'- [{zh} {eng}]({BASE}{f}): source excerpts and museum references.\n' for f,zh,eng in links)+'\n## Provenance\n\nMuseum verification date: 2026-10-04. Station compilation date: 2026-10-05. Site update: 2026-10-09. Contact tzesmann@gmail.com. Individual source URLs and limitations are listed on each city page.\n'
 (DOCS/'llms.txt').write_text(llms,encoding='utf-8')
 (DOCS/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{BASE}{f}</loc><lastmod>2026-10-09</lastmod></url>' for f in ['', 'cities.html']+[l[0] for l in links])+'</urlset>',encoding='utf-8')
 (DOCS/'robots.txt').write_text('# Project-scoped guidance only. Robots exclusion is effective at the origin root, not this project path.\nUser-agent: *\nAllow: /sanguo-travel/\nSitemap: '+BASE+'sitemap.xml\n',encoding='utf-8')
 print('Built',len(links),'city pages. Gzip bytes:',(DOCS/'data.json.gz').stat().st_size)
if __name__=='__main__':build()
